package cz.pyramidak.kalendar

import android.view.View
import java.time.LocalDate
import kotlin.properties.Delegates

class Kalendar(language: String) {
    private var dny = mutableListOf<Den>()
    private val mesice = mutableListOf<Mesic>()
    private val svatky = mutableListOf<Svatek>()
    private val sezony = mutableListOf<LocalDate>()
    var jazyk: String = language
    val jmena = mutableListOf<Jmeno>()
    var dateNow: LocalDate by Delegates.observable(LocalDate.now()) { _, oldValue, newValue ->
        onDayChanged?.invoke(oldValue, newValue)
    }
    var onDayChanged: ((LocalDate, LocalDate) -> Unit)? = null

    //DEN týdne a pojmenování v CZ,SK
    class Den(val den: Int, val CZ: String, val SK: String, val EN: String) {}

    //MESIC v roce, počet DNU a pojmenování v CZ,SK
    class Mesic(val mesic: Int, val dnu: Int, val CZ: String, val SK: String, val EN: String) {}

    //Jméno v CZ,SK v DEN,MESIC
    class Jmeno(val den: Int, val mesic: Int, val CZ: String, val SK: String) {}

    //SVÁTEK v CZ,SK v DEN,MESIC obchody ZAVRENOcz
    class Svatek(val den: Int, val mesic: Int, val CZ: String, val SK: String, val zavrenoCZ: Boolean = false) {}

    //GET DEN
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    fun getDenJmeno(den: Int): String {
        val first: Den? = dny.find { it.den == den }
        return when (jazyk) {
            "SK" -> first?.SK ?:""
            "CZ" -> first?.CZ ?:""
            else -> first?.EN ?:""
        }
    }
    fun getDenJmeno(datum: LocalDate): String {
        return getDenJmeno(datum.dayOfWeek.value)
    }

    //GET MĚSÍC
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    fun prestupnyRok(datum: LocalDate): Boolean {
        return datum.isLeapYear
    }
    fun prestupnyRok(rok: Int): Boolean {
        return prestupnyRok(LocalDate.of(rok, 2,28))
    }
    fun getMesic(mesic: Int): String {
        val first: Mesic? = mesice.find { it.mesic == mesic }
        return when (jazyk) {
            "SK" -> first?.SK ?:""
            "CZ" -> first?.CZ ?:""
            else -> first?.EN ?:""
        }
    }
    fun getMesicMaDnu(datum: LocalDate): Int {
        return getMesicMaDnu(datum.monthValue, datum.year)
    }
    fun getMesicMaDnu(mesic: Int, rok: Int): Int {
        var dnu = mesice.find { it.mesic == mesic }!!.dnu
        if (mesic == 2 && prestupnyRok(rok)) dnu += 1
        return dnu
    }
    fun getMesic(datum: LocalDate): String {
        return getMesic(datum.monthValue)
    }

    //GET JMÉNO
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    fun getJmeno(jmeno: String): Jmeno? {
        return when (jazyk) {
            "SK" -> jmena.find { it.SK.equals(jmeno, ignoreCase = true) }
            else -> jmena.find { it.CZ.equals(jmeno, ignoreCase = true) }
        }
    }
    fun isJmeno(jmeno: String): Boolean {
        return getJmeno(jmeno) != null
    }
    fun getDate(jmeno: String, rok: Int): LocalDate? {
        val first = getJmeno(jmeno)
        return if (first != null) LocalDate.of(rok, first.mesic, first.den) else null
    }
    fun getJmeno(den: Int, mesic: Int): String {
        val first = jmena.find { it.mesic == mesic && it.den == den }
        return when (jazyk) {
            "SK" -> first?.SK ?:""
            else -> first?.CZ ?:""
        }
    }
    fun getJmeno(datum: LocalDate): String {
        return getJmeno(datum.dayOfMonth, datum.monthValue)
    }
    fun getJmena(den: Int, mesic: Int): List<String> {
        return when (jazyk) {
            "SK" -> jmena.filter { it.mesic == mesic && it.den == den && it.SK != "" }.map { it.SK }
            else -> jmena.filter { it.mesic == mesic && it.den == den && it.CZ != "" }.map { it.CZ }
        }
    }
    fun getJmena(datum: LocalDate): List<String> {
        return getJmena(datum.dayOfMonth, datum.monthValue)
    }
    fun getJmenaJoin(den: Int, mesic: Int): String {
        var str = getJmena(den, mesic).joinToString(separator = "/") { it }
        if (str.endsWith("/")) str = str.substring(0, str.length - 1)
        return str
    }
    fun getJmenaJoin(datum: LocalDate): String {
        return getJmenaJoin(datum.dayOfMonth, datum.monthValue)
    }
    //GET SVÁTEK
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    fun getZavreno(datum: LocalDate): Int {
        var first = svatky.find { it.mesic == datum.monthValue && it.den == datum.dayOfMonth }
        if (first?.zavrenoCZ != true) first = specialSvatek(datum)
        return if (first?.zavrenoCZ == true) View.VISIBLE else View.INVISIBLE
    }
    fun getSvatek(datum: LocalDate): String {
        var first = svatky.find { it.mesic == datum.monthValue && it.den == datum.dayOfMonth }
        if (first == null) first = specialSvatek(datum)
        return getSvatek(first)
    }
    fun getSvatek(svatek: Svatek?): String {
        return when (jazyk) {
            "SK" -> svatek?.SK ?:""
            else -> svatek?.CZ ?:""
        }
    }
    fun getSvatek(den: Int, mesic: Int): Svatek? {
        return svatky.find { it.mesic == mesic && it.den == den }
    }
    private fun doCount(x2: Double, yi: Int): Double {
        var y: Double = yi.toDouble()
        return (((x2 / y) - (x2 / y).toInt()) * y + 0.1).toInt().toDouble()
    }
    private fun doCount(x2: Int, y: Int): Double {
        return doCount(x2.toDouble(), y)
    }

    fun specialSvatek(datum: LocalDate): Svatek? {
        //Den matek
        var sun = 0
        if (datum.monthValue == 5) {
            for (day in 1..14) {
                if (LocalDate.of(datum.year,5, day).dayOfWeek.value == 7) sun += 1
                if (sun == 2) {
                    if (datum.dayOfMonth == day) return getSvatek(0,0)
                    break
                }
            }
        }
        //Velikonoční pondělí a neděle a Velký pátek
        val k = (datum.year / 100).toInt()
        val p = ((8 * k + 13) / 25).toInt()
        val q = (k / 4).toInt()
        val i = (doCount(datum.year, 19)).toInt()
        val b = doCount(datum.year , 4)
        val c = doCount(datum.year, 7)
        var y = doCount(15 - p + k - q, 30) + 19 * i
        val d = doCount(y, 30).toInt()
        y = doCount(4 + k - q, 7) + 2 * b + 4 * c + 6 * d
        val s = doCount(y,7).toInt()
        var m = 3
        var t = 22 + d + s
        if (t > 31) m += 1
        if (t > 31) t -= 31
        val u = (if (d == 29) 1 else 0) + (if (s == 6) 1 else 0)
        val v = (if (d == 28) 1 else 0) + (if (s == 6) 1 else 0) + (if (i > 10) 1 else 0)
        if (u == 2 || v == 3) t -= 7
        val velikonoce = LocalDate.of(datum.year,m,t)
        if (datum == velikonoce.minusDays(2)) return getSvatek(0,13)
        if (datum == velikonoce) return getSvatek(0,2)
        if (datum == velikonoce.plusDays(1)) return getSvatek(0,1)
        //Čtvero-roční období
        val first = sezony.find { it.dayOfMonth == datum.dayOfMonth && it.monthValue == datum.monthValue && it.year == datum.year }
        if (first == null) {
            if (!sezony.any { it.year == datum.year }) {
                if (datum.dayOfMonth == 20 && datum.monthValue == 3) return getSvatek(0,3)
                if (datum.dayOfMonth == 21 && datum.monthValue == 6) return getSvatek(0,6)
                if (datum.dayOfMonth == 23 && datum.monthValue == 9) return getSvatek(0,9)
                if (datum.dayOfMonth == 21 && datum.monthValue == 12) return getSvatek(0,12)
            }
        } else {
            return getSvatek(0, first.monthValue)
        }
        return null
    }

    init {
        dny.add( Den(1, "Pondělí", "Pondelok", "Monday"))
        dny.add( Den(2, "Úterý", "Utorok", "Tuesday"))
        dny.add( Den(3, "Středa", "Streda", "Wednesday"))
        dny.add( Den(4, "Čtvrtek", "Štvrtok", "Thursday"))
        dny.add( Den(5, "Pátek", "Piatok", "Friday"))
        dny.add( Den(6, "Sobota", "Sobota", "Saturday"))
        dny.add( Den(7, "Neděle", "Nedeľa", "Sunday"))

        mesice.add( Mesic(1, 31, "Leden", "Január", "January"))
        mesice.add( Mesic(2, 28, "Únor", "Február", "February"))
        mesice.add( Mesic(3, 31, "Březen", "Marec", "March"))
        mesice.add( Mesic(4, 30, "Duben", "Apríl", "April"))
        mesice.add( Mesic(5, 31, "Květen", "Máj", "May"))
        mesice.add( Mesic(6, 30, "Červen", "Jún", "Juny"))
        mesice.add( Mesic(7, 31, "Červenec", "Júl", "July"))
        mesice.add( Mesic(8, 31, "Srpen", "August", "August"))
        mesice.add( Mesic(9, 30, "Září", "Septembra", "September"))
        mesice.add( Mesic(10, 31, "Říjen", "Október", "October"))
        mesice.add( Mesic(11, 30, "Listopad", "November", "November"))
        mesice.add( Mesic(12, 31, "Prosinec", "December", "December"))

        jmena.add( Jmeno(2, 1, "", "Alexandra"))
        jmena.add( Jmeno(2, 1, "Karina", "Karina"))
        jmena.add( Jmeno(3, 1, "Radmila", "Daniela"))
        jmena.add( Jmeno(4, 1, "Diana", "Drahoslav"))
        jmena.add( Jmeno(5, 1, "Dalimil", "Andrea"))
        jmena.add( Jmeno(6, 1, "", "Antónia"))
        jmena.add( Jmeno(7, 1, "Vilma", "Bohuslava"))
        jmena.add( Jmeno(8, 1, "Čestmír", "Severín"))
        jmena.add( Jmeno(9, 1, "Vladan", "Alexej"))
        jmena.add( Jmeno(10, 1, "Břetislav", "Dáša"))
        jmena.add( Jmeno(11, 1, "Bohdana", "Malvína"))
        jmena.add( Jmeno(12, 1, "Pravoslav", "Ernest"))
        jmena.add( Jmeno(13, 1, "Edita", "Rastislav"))
        jmena.add( Jmeno(14, 1, "Radovan", "Radovan"))
        jmena.add( Jmeno(15, 1, "Alice", "Dobroslav"))
        jmena.add( Jmeno(16, 1, "Ctirad", "Kristína"))
        jmena.add( Jmeno(17, 1, "Drahoslav", "Nataša"))
        jmena.add( Jmeno(18, 1, "Vladislav", "Bohdana"))
        jmena.add( Jmeno(19, 1, "Doubravka", "Drahomíra"))
        jmena.add( Jmeno(19, 1, "", "Mário"))
        jmena.add( Jmeno(20, 1, "Ilona", "Dalibor"))
        jmena.add( Jmeno(21, 1, "Běla", "Vincent"))
        jmena.add( Jmeno(22, 1, "Slavomír", "Zora"))
        jmena.add( Jmeno(23, 1, "Zdeněk", "Miloš"))
        jmena.add( Jmeno(24, 1, "Milena", "Timotej"))
        jmena.add( Jmeno(25, 1, "Miloš", "Gejza"))
        jmena.add( Jmeno(26, 1, "Zora", "Tamara"))
        jmena.add( Jmeno(27, 1, "Ingrid", "Bohuš"))
        jmena.add( Jmeno(28, 1, "Otýlie", "Alfonz"))
        jmena.add( Jmeno(29, 1, "Zdislava", "Gašpar"))
        jmena.add( Jmeno(30, 1, "Robin", "Ema"))
        jmena.add( Jmeno(31, 1, "Marika", "Emil"))
        jmena.add( Jmeno(1, 2, "Hynek", "Tatiana"))
        jmena.add( Jmeno(2, 2, "Nela", "Erika, Erik"))
        jmena.add( Jmeno(3, 2, "Blažej", "Blažej"))
        jmena.add( Jmeno(4, 2, "Jarmila", "Veronika"))
        jmena.add( Jmeno(5, 2, "Dobromila", "Agáta"))
        jmena.add( Jmeno(6, 2, "Vanda", "Dorota"))
        jmena.add( Jmeno(7, 2, "Veronika", "Vanda"))
        jmena.add( Jmeno(8, 2, "Milada", "Zoja"))
        jmena.add( Jmeno(9, 2, "Apolena", "Zdenko"))
        jmena.add( Jmeno(10, 2, "Mojmír", "Gabriela"))
        jmena.add( Jmeno(11, 2, "Božena", "Dezider"))
        jmena.add( Jmeno(12, 2, "Slavěna", "Perla"))
        jmena.add( Jmeno(13, 2, "Věnceslav", "Arpád"))
        jmena.add( Jmeno(14, 2, "VALENTÝN", "VALENTÝN"))
        jmena.add( Jmeno(15, 2, "Jiřina", "Pravoslav"))
        jmena.add( Jmeno(16, 2, "Ljuba", "Ida, Liana"))
        jmena.add( Jmeno(17, 2, "Miloslava", "Miloslava"))
        jmena.add( Jmeno(18, 2, "Gizela", "Jaromír"))
        jmena.add( Jmeno(19, 2, "Patrik", "Vlasta"))
        jmena.add( Jmeno(20, 2, "Oldřich", "Lívia"))
        jmena.add( Jmeno(21, 2, "Lenka", "Eleonóra"))
        jmena.add( Jmeno(22, 2, "Petr", "Etela"))
        jmena.add( Jmeno(23, 2, "Svatopluk", "Roman"))
        jmena.add( Jmeno(23, 2, "", "Romana"))
        jmena.add( Jmeno(24, 2, "Matěj", "Matej"))
        jmena.add( Jmeno(25, 2, "Liliana", "Frederik"))
        jmena.add( Jmeno(25, 2, "", "Frederika"))
        jmena.add( Jmeno(26, 2, "Dorota", "Viktor"))
        jmena.add( Jmeno(27, 2, "Alexandr", "Alexander"))
        jmena.add( Jmeno(28, 2, "Lumír", "Zlatica"))
        jmena.add( Jmeno(29, 2, "Horymír", "Radomír"))
        jmena.add( Jmeno(1, 3, "Bedřich", "Albín"))
        jmena.add( Jmeno(2, 3, "Anežka", "Anežka"))
        jmena.add( Jmeno(3, 3, "Kamil", "Bohumil"))
        jmena.add( Jmeno(3, 3, "", "Bohumila"))
        jmena.add( Jmeno(4, 3, "Stela", "Kazimír"))
        jmena.add( Jmeno(5, 3, "Kazimír", "Fridrich"))
        jmena.add( Jmeno(6, 3, "Miroslav", "Radoslav"))
        jmena.add( Jmeno(6, 3, "", "Radoslava"))
        jmena.add( Jmeno(7, 3, "Tomáš", "Tomáš"))
        jmena.add( Jmeno(8, 3, "Gabriela", "Alan, Alana"))
        jmena.add( Jmeno(9, 3, "Františka", "Františka"))
        jmena.add( Jmeno(9, 3, "Rebeka", ""))
        jmena.add( Jmeno(10, 3, "Viktorie", "Bruno, Branislav"))
        jmena.add( Jmeno(11, 3, "Anděla", "Angela"))
        jmena.add( Jmeno(11, 3, "", "Angelika"))
        jmena.add( Jmeno(12, 3, "Řehoř", "Gregor"))
        jmena.add( Jmeno(13, 3, "Růžena", "Vlastimil"))
        jmena.add( Jmeno(14, 3, "Rút", "Matilda"))
        jmena.add( Jmeno(14, 3, "Matilda", ""))
        jmena.add( Jmeno(15, 3, "Ida", "Svetlana"))
        jmena.add( Jmeno(16, 3, "Elena", "Boleslav"))
        jmena.add( Jmeno(16, 3, "Ella", ""))
        jmena.add( Jmeno(16, 3, "Herbert", ""))
        jmena.add( Jmeno(17, 3, "Vlastimil", "Ľubica"))
        jmena.add( Jmeno(18, 3, "Eduard", "Eduard"))
        jmena.add( Jmeno(19, 3, "Josef", "Jozef"))
        jmena.add( Jmeno(20, 3, "Světlana", "Víťazoslav"))
        jmena.add( Jmeno(20, 3, "", "Klaudius"))
        jmena.add( Jmeno(21, 3, "Radek", "Blahoslav"))
        jmena.add( Jmeno(22, 3, "Leona", "Beňadik"))
        jmena.add( Jmeno(23, 3, "Ivona", "Adrián"))
        jmena.add( Jmeno(24, 3, "Gabriel", "Gabriel"))
        jmena.add( Jmeno(25, 3, "Marián", "Marián"))
        jmena.add( Jmeno(26, 3, "Emanuel", "Emanuel"))
        jmena.add( Jmeno(27, 3, "Dita", "Alena"))
        jmena.add( Jmeno(28, 3, "Soňa", "Soňa"))
        jmena.add( Jmeno(29, 3, "Taťána", "Miroslav"))
        jmena.add( Jmeno(30, 3, "Arnošt", "Vieroslava"))
        jmena.add( Jmeno(31, 3, "Kvído", "Benjamín"))
        jmena.add( Jmeno(1, 4, "Hugo", "Hugo"))
        jmena.add( Jmeno(2, 4, "Erika", "Zita"))
        jmena.add( Jmeno(3, 4, "Richard", "Richard"))
        jmena.add( Jmeno(4, 4, "Ivana", "Izidor"))
        jmena.add( Jmeno(5, 4, "Miroslava", "Miroslava"))
        jmena.add( Jmeno(5, 4, "Mirka", ""))
        jmena.add( Jmeno(6, 4, "Vendula", "Irena"))
        jmena.add( Jmeno(6, 4, "Venuše", ""))
        jmena.add( Jmeno(7, 4, "Heřman", "Zoltán"))
        jmena.add( Jmeno(7, 4, "Hermína", ""))
        jmena.add( Jmeno(8, 4, "Ema", "Albert"))
        jmena.add( Jmeno(9, 4, "Dušan", "Milena"))
        jmena.add( Jmeno(10, 4, "Darja", "Igor"))
        jmena.add( Jmeno(11, 4, "Izabela", "Július"))
        jmena.add( Jmeno(12, 4, "Julius", "Estera"))
        jmena.add( Jmeno(13, 4, "Aleš", "Aleš"))
        jmena.add( Jmeno(14, 4, "Vincenc", "Justina"))
        jmena.add( Jmeno(15, 4, "Anastázie", "Fedor"))
        jmena.add( Jmeno(16, 4, "Irena", "Dana"))
        jmena.add( Jmeno(16, 4, "Bernadeta", "Danica"))
        jmena.add( Jmeno(17, 4, "Rudolf", "Rudolf"))
        jmena.add( Jmeno(18, 4, "Valérie", "Valér"))
        jmena.add( Jmeno(19, 4, "Rostislav", "Jela"))
        jmena.add( Jmeno(20, 4, "Marcela", "Marcel"))
        jmena.add( Jmeno(21, 4, "Alexandra", "Ervín"))
        jmena.add( Jmeno(22, 4, "Evženie", "Slavomír"))
        jmena.add( Jmeno(23, 4, "Vojtěch", "Vojtech"))
        jmena.add( Jmeno(24, 4, "Jiří", "Juraj"))
        jmena.add( Jmeno(25, 4, "Marek", "Marek"))
        jmena.add( Jmeno(26, 4, "Oto", "Jaroslava"))
        jmena.add( Jmeno(27, 4, "Jaroslav", "Jaroslav"))
        jmena.add( Jmeno(28, 4, "Vlastislav", "Jarmila"))
        jmena.add( Jmeno(29, 4, "Robert", "Lea"))
        jmena.add( Jmeno(30, 4, "Blahoslav", "Anastázia"))
        jmena.add( Jmeno(2, 5, "Zikmund", "Žigmund"))
        jmena.add( Jmeno(3, 5, "Alexej", "Galina"))
        jmena.add( Jmeno(4, 5, "Květoslav", "Florián"))
        jmena.add( Jmeno(5, 5, "Klaudie", "Lesia"))
        jmena.add( Jmeno(5, 5, "", "Lesana"))
        jmena.add( Jmeno(6, 5, "Radoslav", "Hermína"))
        jmena.add( Jmeno(7, 5, "Stanislav", "Monika"))
        jmena.add( Jmeno(8, 5, "", "Ingrida"))
        jmena.add( Jmeno(9, 5, "Ctibor", "Roland"))
        jmena.add( Jmeno(10, 5, "Blažena", "Viktória"))
        jmena.add( Jmeno(11, 5, "Svatava", "Blažena"))
        jmena.add( Jmeno(12, 5, "Pankrác", "Pankrác"))
        jmena.add( Jmeno(13, 5, "Servác", "Servác"))
        jmena.add( Jmeno(14, 5, "Bonifác", "Bonifác"))
        jmena.add( Jmeno(15, 5, "Žofie", "Žofia"))
        jmena.add( Jmeno(15, 5, "", "Sofia"))
        jmena.add( Jmeno(16, 5, "Přemysl", "Svetozár"))
        jmena.add( Jmeno(17, 5, "Aneta", "Gizela"))
        jmena.add( Jmeno(18, 5, "Nataša", "Viola"))
        jmena.add( Jmeno(19, 5, "Ivo", "Gertrúda"))
        jmena.add( Jmeno(20, 5, "Zbyšek", "Bernard"))
        jmena.add( Jmeno(21, 5, "Monika", "Zina"))
        jmena.add( Jmeno(22, 5, "Emil", "Júlia"))
        jmena.add( Jmeno(22, 5, "", "Juliana"))
        jmena.add( Jmeno(23, 5, "Vladimír", "Želmíra"))
        jmena.add( Jmeno(24, 5, "Jana", "Ela"))
        jmena.add( Jmeno(24, 5, "Vanesa", ""))
        jmena.add( Jmeno(25, 5, "Viola", "Urban"))
        jmena.add( Jmeno(26, 5, "Filip", "Dušan"))
        jmena.add( Jmeno(27, 5, "Valdemar", "Iveta"))
        jmena.add( Jmeno(28, 5, "Vilém", "Viliam"))
        jmena.add( Jmeno(29, 5, "Maxmilián", "Vilma"))
        jmena.add( Jmeno(30, 5, "Ferdinand", "Ferdinand"))
        jmena.add( Jmeno(31, 5, "Kamila", "Petrana"))
        jmena.add( Jmeno(31, 5, "", "Petronela"))
        jmena.add( Jmeno(1, 6, "Laura", "Žaneta"))
        jmena.add( Jmeno(2, 6, "Jarmil", "Xénia"))
        jmena.add( Jmeno(2, 6, "", "Oxana"))
        jmena.add( Jmeno(3, 6, "Tamara", "Karolína"))
        jmena.add( Jmeno(4, 6, "Dalibor", "Lenka"))
        jmena.add( Jmeno(5, 6, "Dobroslav", "Laura"))
        jmena.add( Jmeno(6, 6, "Norbert", "Norbert"))
        jmena.add( Jmeno(7, 6, "Iveta", "Róbert"))
        jmena.add( Jmeno(7, 6, "Slavoj", ""))
        jmena.add( Jmeno(8, 6, "Medard", "Medard"))
        jmena.add( Jmeno(9, 6, "Stanislava", "Stanislava"))
        jmena.add( Jmeno(10, 6, "Gita", "Margaréta"))
        jmena.add( Jmeno(11, 6, "Bruno", "Dobroslava"))
        jmena.add( Jmeno(12, 6, "Antonie", "Zlatko"))
        jmena.add( Jmeno(13, 6, "Antonín", "Anton"))
        jmena.add( Jmeno(14, 6, "Roland", "Vasil"))
        jmena.add( Jmeno(15, 6, "Vít", "Vít"))
        jmena.add( Jmeno(16, 6, "Zbyněk", "Blanka"))
        jmena.add( Jmeno(16, 6, "", "Bianka"))
        jmena.add( Jmeno(17, 6, "Adolf", "Adolf"))
        jmena.add( Jmeno(18, 6, "Milan", "Vratislav"))
        jmena.add( Jmeno(19, 6, "Leoš", "Alfréd"))
        jmena.add( Jmeno(20, 6, "Květa", "Valéria"))
        jmena.add( Jmeno(21, 6, "Alois", "Alojz"))
        jmena.add( Jmeno(22, 6, "Pavla", "Paulína"))
        jmena.add( Jmeno(23, 6, "Zdeňka", "Sidónia"))
        jmena.add( Jmeno(24, 6, "Jan", "Ján"))
        jmena.add( Jmeno(25, 6, "Ivan", "Olívia"))
        jmena.add( Jmeno(25, 6, "", "Tadeáš"))
        jmena.add( Jmeno(26, 6, "Adriana", "Adriána"))
        jmena.add( Jmeno(27, 6, "Ladislav", "Ladislav"))
        jmena.add( Jmeno(27, 6, "", "Ladislava"))
        jmena.add( Jmeno(28, 6, "Lubomír", "Beáta"))
        jmena.add( Jmeno(29, 6, "Petr", "Peter"))
        jmena.add( Jmeno(29, 6, "Pavel", "Pavol"))
        jmena.add( Jmeno(29, 6, "", "Petra"))
        jmena.add( Jmeno(30, 6, "Šárka", "Melánia"))
        jmena.add( Jmeno(1, 7, "Jaroslava", "Diana"))
        jmena.add( Jmeno(2, 7, "Patrície", "Berta"))
        jmena.add( Jmeno(3, 7, "Radomír", "Miloslav"))
        jmena.add( Jmeno(4, 7, "Prokop", "Prokop"))
        jmena.add( Jmeno(5, 7, "Cyril", "Cyril"))
        jmena.add( Jmeno(5, 7, "Metoděj", "Metod"))
        jmena.add( Jmeno(6, 7, "", "Patrik"))
        jmena.add( Jmeno(6, 7, "", "Patrícia"))
        jmena.add( Jmeno(7, 7, "Bohuslava", "Oliver"))
        jmena.add( Jmeno(8, 7, "Nora", "Ivan"))
        jmena.add( Jmeno(9, 7, "Drahoslava", "Lujza"))
        jmena.add( Jmeno(10, 7, "Libuše", ""))
        jmena.add( Jmeno(10, 7, "Amálie", "Amália"))
        jmena.add( Jmeno(11, 7, "Olga", "Milota"))
        jmena.add( Jmeno(12, 7, "Bořek", "Nina"))
        jmena.add( Jmeno(13, 7, "Markéta", "Margita"))
        jmena.add( Jmeno(14, 7, "Karolína", "Kamil"))
        jmena.add( Jmeno(15, 7, "Jindřich", "Henrich"))
        jmena.add( Jmeno(16, 7, "Luboš", "Drahomír"))
        jmena.add( Jmeno(17, 7, "Martina", "Bohuslav"))
        jmena.add( Jmeno(18, 7, "Drahomíra", "Kamila"))
        jmena.add( Jmeno(19, 7, "Čeněk", "Dušana"))
        jmena.add( Jmeno(20, 7, "Ilja", "Iľja, Eliáš"))
        jmena.add( Jmeno(21, 7, "Vítězslav", "Daniel"))
        jmena.add( Jmeno(22, 7, "Magdaléna", "Magdaléna"))
        jmena.add( Jmeno(23, 7, "Libor", "Oľga"))
        jmena.add( Jmeno(24, 7, "Kristýna", "Vladimír"))
        jmena.add( Jmeno(25, 7, "Jakub", "Jakub"))
        jmena.add( Jmeno(26, 7, "Anna", "Anna, Hana"))
        jmena.add( Jmeno(27, 7, "Věroslav", "Božena"))
        jmena.add( Jmeno(28, 7, "Viktor", "Krištof"))
        jmena.add( Jmeno(29, 7, "Marta", "Marta"))
        jmena.add( Jmeno(30, 7, "Bořivoj", "Libuša"))
        jmena.add( Jmeno(31, 7, "Ignác", "Ignác"))
        jmena.add( Jmeno(1, 8, "Oskar", "Božidara"))
        jmena.add( Jmeno(2, 8, "Gustav", "Gustáv"))
        jmena.add( Jmeno(3, 8, "Miluše", "Jerguš"))
        jmena.add( Jmeno(4, 8, "Dominik", "Dominika"))
        jmena.add( Jmeno(4, 8, "", "Dominik"))
        jmena.add( Jmeno(5, 8, "Kristián", "Hortenzia"))
        jmena.add( Jmeno(6, 8, "Oldřiška", "Jozefína"))
        jmena.add( Jmeno(7, 8, "Lada", "Štefánia"))
        jmena.add( Jmeno(8, 8, "Soběslav", "Oskar"))
        jmena.add( Jmeno(9, 8, "Roman", "Ľubomíra"))
        jmena.add( Jmeno(10, 8, "Vavřinec", "Vavrinec"))
        jmena.add( Jmeno(11, 8, "Zuzana", "Zuzana"))
        jmena.add( Jmeno(12, 8, "Klára", "Darina"))
        jmena.add( Jmeno(13, 8, "Alena", "Ľubomír"))
        jmena.add( Jmeno(14, 8, "Alan", "Mojmír"))
        jmena.add( Jmeno(15, 8, "Hana", "Marcela"))
        jmena.add( Jmeno(16, 8, "Jáchym", "Leonard"))
        jmena.add( Jmeno(17, 8, "Petra", "Milica"))
        jmena.add( Jmeno(18, 8, "", "Elena"))
        jmena.add( Jmeno(18, 8, "Helena", "Helena"))
        jmena.add( Jmeno(19, 8, "Ludvík", "Lýdia"))
        jmena.add( Jmeno(20, 8, "Bernard", "Anabela"))
        jmena.add( Jmeno(21, 8, "Johana", "Jana"))
        jmena.add( Jmeno(22, 8, "Bohuslav", "Tichomír"))
        jmena.add( Jmeno(23, 8, "Sandra", "Filip"))
        jmena.add( Jmeno(24, 8, "Bartoloměj", "Bartolomej"))
        jmena.add( Jmeno(25, 8, "Radim", "Ľudovít"))
        jmena.add( Jmeno(26, 8, "Luděk", "Samuel"))
        jmena.add( Jmeno(27, 8, "Otakar", "Silvia"))
        jmena.add( Jmeno(28, 8, "Augustýn", "Augustín"))
        jmena.add( Jmeno(29, 8, "Evelína", "Nikola"))
        jmena.add( Jmeno(29, 8, "", "Nikolaj"))
        jmena.add( Jmeno(30, 8, "Vladěna", "Ružena"))
        jmena.add( Jmeno(31, 8, "Pavlína", "Nora"))
        jmena.add( Jmeno(1, 9, "Linda", "Drahoslava"))
        jmena.add( Jmeno(1, 9, "Samuel", ""))
        jmena.add( Jmeno(2, 9, "Adéla", "Linda"))
        jmena.add( Jmeno(2, 9, "", "Rebeka"))
        jmena.add( Jmeno(3, 9, "Bronislav", "Belo"))
        jmena.add( Jmeno(4, 9, "Jindřiška", "Rozália"))
        jmena.add( Jmeno(5, 9, "Boris", "Regina"))
        jmena.add( Jmeno(6, 9, "Boleslav", "Alica"))
        jmena.add( Jmeno(7, 9, "Regina", "Marianna"))
        jmena.add( Jmeno(8, 9, "Mariana", "Miriama"))
        jmena.add( Jmeno(9, 9, "Daniela", "Martina"))
        jmena.add( Jmeno(10, 9, "Irma", "Oleg"))
        jmena.add( Jmeno(11, 9, "Denisa", "Bystrík"))
        jmena.add( Jmeno(12, 9, "Marie", "Mária"))
        jmena.add( Jmeno(13, 9, "Lubor", "Ctibor"))
        jmena.add( Jmeno(14, 9, "Radka", "Ľudomil"))
        jmena.add( Jmeno(15, 9, "Jolana", "Jolana"))
        jmena.add( Jmeno(16, 9, "Ludmila", "Ľudmila"))
        jmena.add( Jmeno(17, 9, "Naděžda", "Olympia"))
        jmena.add( Jmeno(18, 9, "Kryštof", "Eugénia"))
        jmena.add( Jmeno(19, 9, "Zita", "Konštantín"))
        jmena.add( Jmeno(20, 9, "Oleg", "Ľuboslav"))
        jmena.add( Jmeno(20, 9, "", "Ľuboslava"))
        jmena.add( Jmeno(21, 9, "Matouš", "Matúš"))
        jmena.add( Jmeno(22, 9, "Darina", "Móric"))
        jmena.add( Jmeno(23, 9, "Berta", "Zdenka"))
        jmena.add( Jmeno(24, 9, "Jaromír", "Ľuboš"))
        jmena.add( Jmeno(24, 9, "", "Ľubor"))
        jmena.add( Jmeno(25, 9, "Zlata", "Vladislav"))
        jmena.add( Jmeno(26, 9, "Andrea", "Edita"))
        jmena.add( Jmeno(27, 9, "Jonáš", "Cyprián"))
        jmena.add( Jmeno(28, 9, "Václav", "Václav"))
        jmena.add( Jmeno(29, 9, "Michal", "Michal"))
        jmena.add( Jmeno(29, 9, "Michael", "Michaela"))
        jmena.add( Jmeno(30, 9, "Jeroným", "Jarolím"))
        jmena.add( Jmeno(1, 10, "Igor", "Arnold"))
        jmena.add( Jmeno(2, 10, "Olívie", "Levoslav"))
        jmena.add( Jmeno(2, 10, "Oliver", ""))
        jmena.add( Jmeno(3, 10, "Bohumil", "Stela"))
        jmena.add( Jmeno(4, 10, "František", "František"))
        jmena.add( Jmeno(5, 10, "Eliška", "Viera"))
        jmena.add( Jmeno(6, 10, "Hanuš", "Natália"))
        jmena.add( Jmeno(7, 10, "Justýna", "Eliška"))
        jmena.add( Jmeno(8, 10, "Věra", "Brigita"))
        jmena.add( Jmeno(9, 10, "Štefan", "Dionýz"))
        jmena.add( Jmeno(9, 10, "Sára", ""))
        jmena.add( Jmeno(10, 10, "Marina", "Slavomíra"))
        jmena.add( Jmeno(11, 10, "Andrej", "Valentína"))
        jmena.add( Jmeno(12, 10, "Marcel", "Maximilián"))
        jmena.add( Jmeno(13, 10, "Renáta", "Koloman"))
        jmena.add( Jmeno(14, 10, "Agáta", "Boris"))
        jmena.add( Jmeno(15, 10, "Tereza", "Terézia"))
        jmena.add( Jmeno(16, 10, "Havel", "Vladimíra"))
        jmena.add( Jmeno(17, 10, "Hedvika", "Hedviga"))
        jmena.add( Jmeno(18, 10, "Lukáš", "Lukáš"))
        jmena.add( Jmeno(19, 10, "Michala", "Kristián"))
        jmena.add( Jmeno(19, 10, "Michaela", ""))
        jmena.add( Jmeno(20, 10, "Vendelín", "Vendelín"))
        jmena.add( Jmeno(21, 10, "Brigita", "Uršuľa"))
        jmena.add( Jmeno(22, 10, "Sabina", "Sergej"))
        jmena.add( Jmeno(23, 10, "Teodor", "Alojzia"))
        jmena.add( Jmeno(24, 10, "Nina", "Kvetoslava"))
        jmena.add( Jmeno(25, 10, "Beáta", "Aurel"))
        jmena.add( Jmeno(26, 10, "Erik", "Demeter"))
        jmena.add( Jmeno(27, 10, "Šarlota", "Sabína"))
        jmena.add( Jmeno(27, 10, "Zoe", ""))
        jmena.add( Jmeno(28, 10, "Jidáš", "Dobromila"))
        jmena.add( Jmeno(29, 10, "Silvie", "Klára"))
        jmena.add( Jmeno(29, 10, "Sylva", ""))
        jmena.add( Jmeno(30, 10, "Tadeáš", "Šimon"))
        jmena.add( Jmeno(30, 10, "", "Simona"))
        jmena.add( Jmeno(31, 10, "Štěpánka", "Aurélia"))
        jmena.add( Jmeno(1, 11, "Felix", "Denis"))
        jmena.add( Jmeno(1, 11, "", "Denisa"))
        jmena.add( Jmeno(3, 11, "Hubert", "Hubert"))
        jmena.add( Jmeno(4, 11, "Karel", "Karol"))
        jmena.add( Jmeno(4, 11, "Karla", "Karol"))
        jmena.add( Jmeno(5, 11, "Miriam", "Imrich"))
        jmena.add( Jmeno(6, 11, "Liběna", "Renáta"))
        jmena.add( Jmeno(7, 11, "Saskie", "René"))
        jmena.add( Jmeno(8, 11, "Bohumír", "Bohumír"))
        jmena.add( Jmeno(9, 11, "Bohdan", "Teodor"))
        jmena.add( Jmeno(10, 11, "Evžen", "Tibor"))
        jmena.add( Jmeno(11, 11, "Martin", "Martin"))
        jmena.add( Jmeno(11, 11, "", "Maroš"))
        jmena.add( Jmeno(12, 11, "Benedikt", "Svätopluk"))
        jmena.add( Jmeno(13, 11, "Tibor", "Stanislav"))
        jmena.add( Jmeno(14, 11, "Sáva", "Irma"))
        jmena.add( Jmeno(15, 11, "Leopold", "Leopold"))
        jmena.add( Jmeno(16, 11, "Otmar", "Agnesa"))
        jmena.add( Jmeno(17, 11, "Mahulena", "Klaudia"))
        jmena.add( Jmeno(18, 11, "Romana", "Eugen"))
        jmena.add( Jmeno(19, 11, "Alžběta", "Alžbeta"))
        jmena.add( Jmeno(20, 11, "Nikola", "Félix"))
        jmena.add( Jmeno(21, 11, "Albert", "Elvíra"))
        jmena.add( Jmeno(22, 11, "Cecílie", "Cecília"))
        jmena.add( Jmeno(23, 11, "Klement", "Klement"))
        jmena.add( Jmeno(24, 11, "Emílie", "Emília"))
        jmena.add( Jmeno(24, 11, "Emily", "Emily"))
        jmena.add( Jmeno(25, 11, "Kateřina", "Katarína"))
        jmena.add( Jmeno(26, 11, "Artur", "Kornel"))
        jmena.add( Jmeno(27, 11, "Xenie", "Milan"))
        jmena.add( Jmeno(28, 11, "René", "Henrieta"))
        jmena.add( Jmeno(29, 11, "Zina", "Vratko"))
        jmena.add( Jmeno(30, 11, "Ondřej", "Ondrej"))
        jmena.add( Jmeno(30, 11, "", "Andrej"))
        jmena.add( Jmeno(1, 12, "Iva", "Edmund"))
        jmena.add( Jmeno(2, 12, "Blanka", "Bibiána"))
        jmena.add( Jmeno(3, 12, "Svatoslav", "Oldrich"))
        jmena.add( Jmeno(4, 12, "Barbora", "Barbora"))
        jmena.add( Jmeno(4, 12, "", "Barbara"))
        jmena.add( Jmeno(5, 12, "Jitka", "Oto"))
        jmena.add( Jmeno(6, 12, "Mikuláš", "Mikuláš"))
        jmena.add( Jmeno(7, 12, "Benjamín", "Ambróz"))
        jmena.add( Jmeno(8, 12, "Květoslava", "Marína"))
        jmena.add( Jmeno(9, 12, "Vratislav", "Izabela"))
        jmena.add( Jmeno(10, 12, "Julie", "Radúz"))
        jmena.add( Jmeno(11, 12, "Dana", "Hilda"))
        jmena.add( Jmeno(12, 12, "Simona", "Otília"))
        jmena.add( Jmeno(13, 12, "Lucie", "Lucia"))
        jmena.add( Jmeno(14, 12, "Lýdie", "Branislava"))
        jmena.add( Jmeno(14, 12, "", "Bronislava"))
        jmena.add( Jmeno(15, 12, "Radana", "Ivica"))
        jmena.add( Jmeno(16, 12, "Albína", "Albína"))
        jmena.add( Jmeno(17, 12, "Daniel", "Kornélia"))
        jmena.add( Jmeno(18, 12, "Miloslav", "Sláva"))
        jmena.add( Jmeno(19, 12, "Ester", "Judita"))
        jmena.add( Jmeno(20, 12, "Dagmar", "Dagmara"))
        jmena.add( Jmeno(21, 12, "Natálie", "Bohdan"))
        jmena.add( Jmeno(22, 12, "Šimon", "Adela"))
        jmena.add( Jmeno(23, 12, "Vlasta", "Nadežda"))
        jmena.add( Jmeno(24, 12, "Adam", "Adam"))
        jmena.add( Jmeno(24, 12, "Eva", "Eva"))
        jmena.add( Jmeno(26, 12, "Štěpán", "Štefan"))
        jmena.add( Jmeno(27, 12, "Žaneta", "Filoména"))
        jmena.add( Jmeno(28, 12, "Bohumila", "Ivana"))
        jmena.add( Jmeno(28, 12, "", "Ivona"))
        jmena.add( Jmeno(29, 12, "Judita", "Milada"))
        jmena.add( Jmeno(30, 12, "David", "Dávid"))
        jmena.add( Jmeno(31, 12, "Silvestr", "Silvester"))

        svatky.add( Svatek(0, 0, "Den matek", "Deň matiek"))
        svatky.add( Svatek(0, 1, "Velikonoční pondělí", "Veľkonočný pondelok", true))
        svatky.add( Svatek(0, 2, "Velikonoční neděle", "Boží hod velikonoční"))
        svatky.add( Svatek(0, 3, "První jarní den", "Prvý jarný deň"))
        svatky.add( Svatek(0, 6, "První letní den", "Prvý letný deň"))
        svatky.add( Svatek(0, 9, "První podzimní den", "Prvý jesenný deň, False"))
        svatky.add( Svatek(0, 12, "První zimní den", "Prvý zimný deň, False"))
        svatky.add( Svatek(0, 13, "Velký pátek", "Veľký piatok"))
        svatky.add( Svatek(1, 1, "Nový rok, Den obnovy samostatného českého státu 1993", "Deň vzniku Slovenskej republiky 1993", true))
        svatky.add( Svatek(6, 1, "Tři králové (křesťanský svátek)", "Traja Králi (památný den)"))
        svatky.add( Svatek(1, 5, "Svátek práce", "Sviatok práce"))
        svatky.add( Svatek(12, 3, "Den vstupu ČR do NATO 1999 (významný den)", ""))
        svatky.add( Svatek(28, 10, "Den vzniku samostatného Československa 1918", "Deň vzniku samostatného Československa 1918 (památný den)", true))
        svatky.add( Svatek(8, 5, "Den vítězství, konec druhé světové války 1945", "Deň víťazstva nad fašizmom 1945", true))
        svatky.add( Svatek(5, 5, "Květnové povstání českého lidu 1945 (významný den)", ""))
        svatky.add( Svatek(1, 6, "Mezinárodní den dětí 1925 (významný den)", "Medzinárodný deň detí 1925 (památný den)"))
        svatky.add( Svatek(17, 11, "Den boje za svobodu a demokracii 1989", "Deň boja za slobodu a demokraciu 1989"))
        svatky.add( Svatek(24, 12, "Štědrý den", "Štedrý deň", true))
        svatky.add( Svatek(25, 12, "1.svátek vánoční", "Prvý sviatok vianočný", true))
        svatky.add( Svatek(26, 12, "2.svátek vánoční", "Druhý sviatok vianočný", true))
        svatky.add( Svatek(5, 7, "Den slovanských věrozvěstů Cyrila a Metoděje 863", "Sviatok svätého Cyrila a svätého Metoda 863"))
        svatky.add( Svatek(6, 7, "Den upálení mistra Jana Husa 1415", ""))
        svatky.add( Svatek(28, 9, "Den české státnosti 929/935", "", true))
        svatky.add( Svatek(29, 8, "", "Výročie Slovenského národného povstania"))
        svatky.add( Svatek(1, 9, "", "Deň Ústavy Slovenskej republiky"))
        svatky.add( Svatek(15, 9, "", "Sedembolestná Panna Mária"))
        svatky.add( Svatek(1, 11, "", "Sviatok Všetkých svätých"))
        svatky.add( Svatek(2, 11, "Památka zesnulých (křesťanský svátek)", ""))
        svatky.add( Svatek(25, 3, "", "Deň zápasu za ľudské práva (památný den)"))
        svatky.add( Svatek(13, 4, "", "Deň nespravodlivo stíhaných (památný den)"))
        svatky.add( Svatek(7, 6, "", "Výročie Memoranda národa slovenského (památný den)"))
        svatky.add( Svatek(5, 7, "", "Deň zahraničných Slovákov (památný den)"))
        svatky.add( Svatek(17, 7, "", "Výročie Deklarácie o zvrchovanosti Slovenskej republiky (památný den)"))
        svatky.add( Svatek(4, 8, "", "Deň Matice slovenskej"))
        svatky.add( Svatek(9, 9, "", "Deň obetí holokaustu a rasového násilia (památný den)"))
        svatky.add( Svatek(19, 9, "", "Deň vzniku Slovenskej národnej rady (památný den)"))
        svatky.add( Svatek(6, 10, "", "Deň obetí Dukly (památný den)"))
        svatky.add( Svatek(27, 10, "", "Deň černovskej tragédie (památný den)"))
        svatky.add( Svatek(29, 10, "", "Výročie narodenia Ľudovíta Štúra (památný den)"))
        svatky.add( Svatek(30, 10, "", "Výročie Deklarácie slovenského národa (památný den)"))
        svatky.add( Svatek(31, 10, "", "Deň reformácie (památný den)"))
        svatky.add( Svatek(30, 12, "", "Vyhlásenia Slovenska za samostatnú cirkevnú provinciu (památný den)"))
        svatky.add( Svatek(8, 3, "Mezinárodní den žen (významný den)", ""))
        svatky.add( Svatek(27, 1, "Den památky obětí holocaustu 1945 (významný den)", ""))
        svatky.add( Svatek(28, 3, "Den narození Jana Ámose Komenského 1592 (významný den)", ""))
        svatky.add( Svatek(7, 4, "Den vzdělanosti, založení Univerzity Karlovy 1348 (významný den)", ""))
        svatky.add( Svatek(15, 5, "Den rodin 1993 (významný den)", "Deň rodin 1993 (památný den)"))
        svatky.add( Svatek(10, 6, "Vyhlazení obce Lidice 1942 (významný den)", ""))
        svatky.add( Svatek(27, 6, "Den památky obětí komunistického režimu 1950 (významný den)", ""))
        svatky.add( Svatek(11, 11, "Den válečných veteránů 1918 (významný den)", ""))

        sezony.add( LocalDate.of(2000, 3, 20))
        sezony.add( LocalDate.of(2001, 3, 20))
        sezony.add( LocalDate.of(2002, 3, 20))
        sezony.add( LocalDate.of(2003, 3, 21))
        sezony.add( LocalDate.of(2004, 3, 20))
        sezony.add( LocalDate.of(2005, 3, 20))
        sezony.add( LocalDate.of(2006, 3, 20))
        sezony.add( LocalDate.of(2007, 3, 21))
        sezony.add( LocalDate.of(2008, 3, 20))
        sezony.add( LocalDate.of(2009, 3, 20))
        sezony.add( LocalDate.of(2010, 3, 20))
        sezony.add( LocalDate.of(2011, 3, 21))
        sezony.add( LocalDate.of(2012, 3, 20))
        sezony.add( LocalDate.of(2013, 3, 20))
        sezony.add( LocalDate.of(2014, 3, 20))
        sezony.add( LocalDate.of(2015, 3, 20))
        sezony.add( LocalDate.of(2016, 3, 20))
        sezony.add( LocalDate.of(2017, 3, 20))
        sezony.add( LocalDate.of(2018, 3, 20))
        sezony.add( LocalDate.of(2019, 3, 20))
        sezony.add( LocalDate.of(2020, 3, 20))
        sezony.add( LocalDate.of(2021, 3, 21))
        sezony.add( LocalDate.of(2022, 3, 20))
        sezony.add( LocalDate.of(2023, 3, 20))
        sezony.add( LocalDate.of(2024, 3, 20))
        sezony.add( LocalDate.of(2025, 3, 20))
        sezony.add( LocalDate.of(2026, 3, 20))
        sezony.add( LocalDate.of(2027, 3, 20))
        sezony.add( LocalDate.of(2028, 3, 20))
        sezony.add( LocalDate.of(2029, 3, 20))
        sezony.add( LocalDate.of(2030, 3, 20))
        sezony.add( LocalDate.of(2031, 3, 20))
        sezony.add( LocalDate.of(2032, 3, 20))
        sezony.add( LocalDate.of(2033, 3, 20))
        sezony.add( LocalDate.of(2034, 3, 20))
        sezony.add( LocalDate.of(2035, 3, 20))
        sezony.add( LocalDate.of(2036, 3, 20))
        sezony.add( LocalDate.of(2037, 3, 20))
        sezony.add( LocalDate.of(2038, 3, 20))
        sezony.add( LocalDate.of(2039, 3, 20))
        sezony.add( LocalDate.of(2040, 3, 20))
        sezony.add( LocalDate.of(2041, 3, 20))
        sezony.add( LocalDate.of(2000, 6, 21))
        sezony.add( LocalDate.of(2001, 6, 21))
        sezony.add( LocalDate.of(2002, 6, 21))
        sezony.add( LocalDate.of(2003, 6, 21))
        sezony.add( LocalDate.of(2004, 6, 21))
        sezony.add( LocalDate.of(2005, 6, 21))
        sezony.add( LocalDate.of(2006, 6, 21))
        sezony.add( LocalDate.of(2007, 6, 21))
        sezony.add( LocalDate.of(2008, 6, 21))
        sezony.add( LocalDate.of(2009, 6, 21))
        sezony.add( LocalDate.of(2010, 6, 21))
        sezony.add( LocalDate.of(2011, 6, 21))
        sezony.add( LocalDate.of(2012, 6, 21))
        sezony.add( LocalDate.of(2013, 6, 21))
        sezony.add( LocalDate.of(2014, 6, 21))
        sezony.add( LocalDate.of(2015, 6, 21))
        sezony.add( LocalDate.of(2016, 6, 21))
        sezony.add( LocalDate.of(2017, 6, 21))
        sezony.add( LocalDate.of(2018, 6, 21))
        sezony.add( LocalDate.of(2019, 6, 21))
        sezony.add( LocalDate.of(2020, 6, 21))
        sezony.add( LocalDate.of(2021, 6, 21))
        sezony.add( LocalDate.of(2022, 6, 21))
        sezony.add( LocalDate.of(2023, 6, 21))
        sezony.add( LocalDate.of(2024, 6, 20))
        sezony.add( LocalDate.of(2025, 6, 21))
        sezony.add( LocalDate.of(2026, 6, 21))
        sezony.add( LocalDate.of(2027, 6, 21))
        sezony.add( LocalDate.of(2028, 6, 20))
        sezony.add( LocalDate.of(2029, 6, 21))
        sezony.add( LocalDate.of(2030, 6, 21))
        sezony.add( LocalDate.of(2031, 6, 21))
        sezony.add( LocalDate.of(2032, 6, 20))
        sezony.add( LocalDate.of(2033, 6, 21))
        sezony.add( LocalDate.of(2034, 6, 21))
        sezony.add( LocalDate.of(2035, 6, 21))
        sezony.add( LocalDate.of(2036, 6, 20))
        sezony.add( LocalDate.of(2037, 6, 21))
        sezony.add( LocalDate.of(2038, 6, 21))
        sezony.add( LocalDate.of(2039, 6, 21))
        sezony.add( LocalDate.of(2040, 6, 20))
        sezony.add( LocalDate.of(2041, 6, 21))
        sezony.add( LocalDate.of(2000, 9, 22))
        sezony.add( LocalDate.of(2001, 9, 23))
        sezony.add( LocalDate.of(2002, 9, 23))
        sezony.add( LocalDate.of(2003, 9, 23))
        sezony.add( LocalDate.of(2004, 9, 22))
        sezony.add( LocalDate.of(2005, 9, 23))
        sezony.add( LocalDate.of(2006, 9, 23))
        sezony.add( LocalDate.of(2007, 9, 23))
        sezony.add( LocalDate.of(2008, 9, 22))
        sezony.add( LocalDate.of(2009, 9, 22))
        sezony.add( LocalDate.of(2010, 9, 23))
        sezony.add( LocalDate.of(2011, 9, 23))
        sezony.add( LocalDate.of(2012, 9, 22))
        sezony.add( LocalDate.of(2013, 9, 22))
        sezony.add( LocalDate.of(2014, 9, 23))
        sezony.add( LocalDate.of(2015, 9, 23))
        sezony.add( LocalDate.of(2016, 9, 22))
        sezony.add( LocalDate.of(2017, 9, 22))
        sezony.add( LocalDate.of(2018, 9, 23))
        sezony.add( LocalDate.of(2019, 9, 23))
        sezony.add( LocalDate.of(2020, 9, 22))
        sezony.add( LocalDate.of(2021, 9, 22))
        sezony.add( LocalDate.of(2022, 9, 23))
        sezony.add( LocalDate.of(2023, 9, 23))
        sezony.add( LocalDate.of(2024, 9, 22))
        sezony.add( LocalDate.of(2025, 9, 22))
        sezony.add( LocalDate.of(2026, 9, 23))
        sezony.add( LocalDate.of(2027, 9, 23))
        sezony.add( LocalDate.of(2028, 9, 22))
        sezony.add( LocalDate.of(2029, 9, 22))
        sezony.add( LocalDate.of(2030, 9, 23))
        sezony.add( LocalDate.of(2031, 9, 23))
        sezony.add( LocalDate.of(2032, 9, 22))
        sezony.add( LocalDate.of(2033, 9, 22))
        sezony.add( LocalDate.of(2034, 9, 23))
        sezony.add( LocalDate.of(2035, 9, 23))
        sezony.add( LocalDate.of(2036, 9, 22))
        sezony.add( LocalDate.of(2037, 9, 22))
        sezony.add( LocalDate.of(2038, 9, 22))
        sezony.add( LocalDate.of(2039, 9, 23))
        sezony.add( LocalDate.of(2040, 9, 22))
        sezony.add( LocalDate.of(2041, 9, 22))
        sezony.add( LocalDate.of(2000, 12, 21))
        sezony.add( LocalDate.of(2001, 12, 21))
        sezony.add( LocalDate.of(2002, 12, 22))
        sezony.add( LocalDate.of(2003, 12, 22))
        sezony.add( LocalDate.of(2004, 12, 21))
        sezony.add( LocalDate.of(2005, 12, 21))
        sezony.add( LocalDate.of(2006, 12, 22))
        sezony.add( LocalDate.of(2007, 12, 22))
        sezony.add( LocalDate.of(2008, 12, 21))
        sezony.add( LocalDate.of(2009, 12, 21))
        sezony.add( LocalDate.of(2010, 12, 22))
        sezony.add( LocalDate.of(2011, 12, 22))
        sezony.add( LocalDate.of(2012, 12, 21))
        sezony.add( LocalDate.of(2013, 12, 21))
        sezony.add( LocalDate.of(2014, 12, 22))
        sezony.add( LocalDate.of(2015, 12, 22))
        sezony.add( LocalDate.of(2016, 12, 21))
        sezony.add( LocalDate.of(2017, 12, 21))
        sezony.add( LocalDate.of(2018, 12, 21))
        sezony.add( LocalDate.of(2019, 12, 22))
        sezony.add( LocalDate.of(2020, 12, 21))
        sezony.add( LocalDate.of(2021, 12, 21))
        sezony.add( LocalDate.of(2022, 12, 21))
        sezony.add( LocalDate.of(2023, 12, 22))
        sezony.add( LocalDate.of(2024, 12, 21))
        sezony.add( LocalDate.of(2025, 12, 21))
        sezony.add( LocalDate.of(2026, 12, 21))
        sezony.add( LocalDate.of(2027, 12, 22))
        sezony.add( LocalDate.of(2028, 12, 21))
        sezony.add( LocalDate.of(2029, 12, 21))
        sezony.add( LocalDate.of(2030, 12, 21))
        sezony.add( LocalDate.of(2031, 12, 22))
        sezony.add( LocalDate.of(2032, 12, 21))
        sezony.add( LocalDate.of(2033, 12, 21))
        sezony.add( LocalDate.of(2034, 12, 21))
        sezony.add( LocalDate.of(2035, 12, 22))
        sezony.add( LocalDate.of(2036, 12, 21))
        sezony.add( LocalDate.of(2037, 12, 21))
        sezony.add( LocalDate.of(2038, 12, 21))
        sezony.add( LocalDate.of(2039, 12, 22))
        sezony.add( LocalDate.of(2040, 12, 21))
        sezony.add( LocalDate.of(2041, 12, 21))
    }



}